name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # ou outra versão, se preferir

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip

    - name: Executar testes
      run: |
        python -m unittest discover -s . -p "*.py"
